name: Update binaries version
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: renovate
        uses: renovatebot/github-action@v43.0.14
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
